// Generated by tools/catalog-town-assets.py from shipped texture bytes.
static const unsigned long long townBackgroundHashes[]={
 0xea66d742a8713f97ull, // tm_e_townback_rich.dds
 0xea15e39a8a6e0701ull, // tm_e_settlement.dds
 0x0dec3bd95db50a33ull, // tm_p_townback.dds
 0xf95920fc9c00db5eull, // tm_s_townback_rich.dds
 0x21e1d04c1cd2002eull, // tm_d_settlement.dds
 0x9cd9d93d85004d89ull, // tm_e_townback_poor.dds
 0x401ddb55e82c923full, // tm_f_townback_rich.dds
 0x3f00dba86c15c5d9ull, // tm_s_settlement.dds
 0x340067055b2d00f3ull, // tm_s_townback_poor.dds
 0xaccbc3f5222cf1b8ull, // tm_f_settlement.dds
 0xd7919eaab87a4452ull, // tm_d_townback_poor.dds
 0xde245ea737096b9aull, // tm_d_townback_rich.dds
 0x75f75f4cd0888b25ull, // tm_f_townback_poor.dds
};
static const unsigned long long townCompanionHashes[]={
 0x6206d502e3e52093ull, // townflagdutch2.dds
 0xbf0d26ce74c2e326ull, // townflageng4.dds
 0x74745b0906a154f0ull, // townflagdutch4.dds
 0x3174925e41437f63ull, // townflagfren2.dds
 0xa0ea49f36ddc8891ull, // flag_dut3.dds
 0x8e68e420a8b28eabull, // flag_fre3.dds
 0x80827ba68c32d80eull, // townflagdutch1.dds
 0xd8cff764c1622e55ull, // townflageng1.dds
 0x0e697f757f2f5aa9ull, // townflagspain4.dds
 0x816409e9ac2588e1ull, // flag_spa2.dds
 0xd34d793861eaf55full, // tm_cloud_02.dds
 0xe8ee9498d66e12bdull, // townflageng3.dds
 0xce84e367dc28d044ull, // flag_spa3.dds
 0x5899349af13c0c16ull, // flag_eng3.dds
 0xd6d80dc6593962a6ull, // flag_fre1.dds
 0x816409e9ac2588e1ull, // townflagspain3.dds
 0x0e8f8893a3180d7dull, // flag_pir0.dds
 0x6206d502e3e52093ull, // flag_dut1.dds
 0xb2eeaca24c024cbbull, // tm_cloud_01.dds
 0xb37dc40482d0ff5dull, // flag_pir1.dds
 0xbb03066e805fede8ull, // townflagspain1.dds
 0x5248b4d16a86b86dull, // townflagspain2.dds
 0x15e3266e7bcb1a41ull, // flag_eng2.dds
 0x5248b4d16a86b86dull, // flag_spa1.dds
 0xbb03066e805fede8ull, // flag_spa0.dds
 0x48bb48ad9d558c44ull, // flag_pir2.dds
 0xfc12a42ea66b44caull, // flag_eng0.dds
 0x82d5ce79a182b088ull, // flag_eng1.dds
 0x9d3bf1dc298aca1eull, // flag_dut2.dds
 0x6819382b13b2de6cull, // townflagfren3.dds
 0xb6d7427abdb52acdull, // flag_fre2.dds
 0x6f9d66598d9a884eull, // townflageng2.dds
 0x80827ba68c32d80eull, // flag_dut0.dds
 0x9caeddbaf0cf90beull, // townflagfren4.dds
 0xfad35ea2d66d161eull, // flag_fre0.dds
 0xe9dc9df9c6988c8aull, // townflagfren1.dds
 0x9d3bf1dc298aca1eull, // townflagdutch3.dds
};
